### ISSUE TITLE
Are you sure you want to use let's here?

### ISSUE THREAD

**Issue by joostf** [joanpadolina/web-app-from-scratch-1920#10]
https://github.com/joanpadolina/web-app-from-scratch-1920/blob/499a7ec27230f4c07978fb8bcb2005170d6be87f/src/js/app.js#L16-L27

https://github.com/cmda-minor-web/best-practices/blob/master/javascript.md#var-let-or-const

**Comment by joanpadolina** [comment]
thanks for the feed I've changed this to a name which makes more sense
