### ISSUE TITLE
Nice use of map and filter.

### ISSUE THREAD

**Issue by tnanhekhan** [joanpadolina/web-app-from-scratch-1920#20]
https://github.com/joanpadolina/web-app-from-scratch-1920/blob/85d3988f6693f60682c84816313f74ba2014f76d/src/modules/data.js#L7

https://github.com/joanpadolina/web-app-from-scratch-1920/blob/85d3988f6693f60682c84816313f74ba2014f76d/src/modules/data.js#L25

**Comment by joanpadolina** [comment]
👍
