### ISSUE TITLE
Code: Modules (Actors) zijn niet aangegeven in de diagrammen

### ISSUE THREAD

**Issue by titmousemees** [joanpadolina/web-app-from-scratch-1920#27]
De modules in de afbeelding hieronder komen niet voor in je diagrammen. Kan je de functies in deze "modules" niet gewoon in app.js zetten?
![Screenshot_10](https://user-images.githubusercontent.com/32935392/74523941-675d4380-4f1e-11ea-97cb-ed381e5b64d8.png)

**Comment by joanpadolina** [comment]
I've merged routings together
