### ISSUE TITLE
Rename files in order to follow the code convention

### ISSUE THREAD

**Issue by titmousemees** [joanpadolina/web-app-from-scratch-1920#3]
Rename the file "createelement.js" to "createElement.js" for exmaple.https://www.robinwieruch.de/javascript-naming-conventions#javascript-naming-conventions-files

**Comment by joostf** [comment]
Nice refernce @meessour ! I added it to our best practices repo:
https://github.com/cmda-minor-web/best-practices/blob/master/README.md

**Comment by joanpadolina** [comment]
I've name mij var and function in a more js type thanks for the reference
