### ISSUE TITLE
Rename function name to getXxx when it returns someting

### ISSUE THREAD

**Issue by titmousemees** [joanpadolina/web-app-from-scratch-1920#6]
https://github.com/joanpadolina/web-app-from-scratch-1920/blob/499a7ec27230f4c07978fb8bcb2005170d6be87f/src/js/app.js#L19

https://github.com/joanpadolina/web-app-from-scratch-1920/blob/499a7ec27230f4c07978fb8bcb2005170d6be87f/src/js/app.js#L31

**Comment by joanpadolina** [comment]
I've changed this to a variable that makes more sense. Still hard to give functions or vars a name haha
