### ISSUE TITLE
Naming function

### ISSUE THREAD

**Issue by nlvo** [joanpadolina/web-app-from-scratch-1920#8]
It would be nice to use a more descriptive function names or maybe add some comments. Maybe something like getRandomCategories or randomCategories. So it will be easier for someone new to get a grasp of what everything does.
 
https://github.com/joanpadolina/web-app-from-scratch-1920/blob/499a7ec27230f4c07978fb8bcb2005170d6be87f/src/js/app.js#L17

**Comment by joanpadolina** [comment]
changed this to a name which makes more sense
